- name: checking image status
  hosts: localhost
  become: yes
  gather_facts: no
 
  tasks:
  - name: run the docker image
    shell: docker run -it -p 7010:80 --name apache -d apache:"{{ image_version }}"
  
  - name: get the ip address
    shell: curl http://169.254.169.254/latest/meta-data/public-ipv4
    register: result
  
  - set_fact: ip_address={{ result.stdout }}

  - pause:
     seconds: 20

  - name: check health of the url
    uri: url=http://{{ ip_address }}:7010
    register: result
    until: result.status == 200

  - debug: msg="Url staus is {{ result.status }}"

  - name: create tag for image
    shell: docker tag apache:"{{ image_version }}" kiranp23/apache:"{{ image_version }}"

  - name: push image to docker hub
    shell: docker push kiranp23/apache:"{{ image_version }}"

  - name: check image exists or not
    shell: docker ps | grep apache
    register: result

  - name: if image is runing
    shell: docker stop apache && docker rm apache
    when: result is succeeded
